name: Update blog posts

on:
  schedule:
    - cron: "0 */12 * * *"   # 6ì‹œê°„ë§ˆë‹¤ ì‹¤í–‰
  workflow_dispatch:        # ìˆ˜ë™ ì‹¤í–‰ ë²„íŠ¼
  push:
    branches: ["main"]

permissions:
  contents: write   # README ìˆ˜ì • ê¶Œí•œ

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://mozmin.tistory.com/rss"   # ğŸ‘‰ ë‚´ í‹°ìŠ¤í† ë¦¬ RSS ì£¼ì†Œ
          max_post_count: 5
          readme_path: README.md
          template: "- [$title]($url)  \n"
          commit_message: "chore: update latest blog posts"
